// <auto-generated />
using System;
using ManufacturingProcessMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturingProcessMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManufacturingProcessMVC.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instrument");

                    b.HasDiscriminator<string>("InstrumentType").HasValue("Instrument");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ManufacturingProcessMVC.Models.ManufacturingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.HasIndex("TapId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("ManufacturingProcessMVC.Models.Drill", b =>
                {
                    b.HasBaseType("ManufacturingProcessMVC.Models.Instrument");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Drill");
                });

            modelBuilder.Entity("ManufacturingProcessMVC.Models.Tap", b =>
                {
                    b.HasBaseType("ManufacturingProcessMVC.Models.Instrument");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreadType")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tap");
                });

            modelBuilder.Entity("ManufacturingProcessMVC.Models.ManufacturingProcess", b =>
                {
                    b.HasOne("ManufacturingProcessMVC.Models.Drill", "Drill")
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingProcessMVC.Models.Tap", "Tap")
                        .WithMany()
                        .HasForeignKey("TapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");

                    b.Navigation("Tap");
                });
#pragma warning restore 612, 618
        }
    }
}
